### ISSUE TITLE
Fonts broken

### ISSUE THREAD

**Issue by matthieugras** [flathub/org.telegram.desktop#49]
![screenshot_20181213_140929](https://user-images.githubusercontent.com/35115728/49940807-91f5db80-fed8-11e8-8cef-decf9fcdce08.png)

This is the wrong font that shows up in the file selection

**Comment by kode54** [comment]
Can we mix this with a different issue as well? Cross posting this one:

com.discordapp.Discord#27

As it appears to affect this as well. No CJK support whatsoever, yet it manages to have the runic script font that I know one Telegram user has for their display name.

**Comment by 49616e** [comment]
CJK fonts used to work (albeit in a rather ugly font) before I updated the telegram flatpak and the kde runtime to the latest version (747c28320ab3 and dcfee2860f76 respectively). Now CJK is totally broken for me as well.


![image](https://user-images.githubusercontent.com/39971507/50387711-447e3780-073e-11e9-8c3b-ce4f7afd8f17.png)

**Comment by matthieugras** [comment]
Would the maintainer of this packages mind to at least do a fucking 2 min test run of the application before pushing broken garbage to stable channels?

**Comment by 49616e** [comment]
I think the problem is that none of the developers understands CJK, and it's rather difficult to care for a language that you can't understand. The CJK support is, and has been somewhat broken on the discord flatpak for some people (including myself) for a very long time, and yet there's not much info on why this is even happening in the first place. https://github.com/flathub/com.discordapp.Discord/issues/27

**Comment by jurf** [comment]
@matthieugras: please avoid language like this. Just because you’re experiencing a rare, hard-to-reproduce bug, doesn’t mean you have to berate the maintainer.

**Comment by jurf** [comment]
If it is any help, I experienced a bug similar to this a while back – at least the symptoms were the same, mono-space font application-wide. A restart fixed it at the time. IIRC it came out of nowhere, I’ll try to pay more heed to it if it happens again.

**Comment by grulja** [comment]
This might be an issue in gtk maybe, because it's a gtk dialog, no idea, but we are working on making Telegram in Flathub official, which means it could be maintained by the developers and one thing I discussed with them was using native file dialogs, this would result into using portals and not having this dialog at all.

**Comment by ahayzen** [comment]
CJK fail within the Telegram Qt app itself for me as well (eg if someone sends me a message with CJK characters).

I have also noticed that the 5.9 KDE runtime I cannot use mozc to type CJK whereas with the 5.11 KDE runtime (eg with org.kate.kate//master) i can.  Maybe once the 5.12 runtime is out this will help the Qt input issues.

It's strange how it has suddenly affected both the Qt text and gtk dialogs though, maybe something in the runtime has regressed ?

**Comment by AsciiWolf** [comment]
Same issue here on Fedora 29.

**Comment by grulja** [comment]
The dialog font issue should be fixed, telegram should be using portals now.

Commit for reference: https://github.com/flathub/org.telegram.desktop/commit/f9041d1f765fa03f048a0f9cb38d052130468bb7

**Comment by kenya888** [comment]
Hi @grulja and all, thank you for yourgreat work of telegram app on flatpak maintenance!!

> The dialog font issue should be fixed, telegram should be using portals now.
> 
> Commit for reference: [f9041d1](https://github.com/flathub/org.telegram.desktop/commit/f9041d1f765fa03f048a0f9cb38d052130468bb7)

I think this PR has a typo. Is this related something to this issue?
https://github.com/flathub/org.telegram.desktop/commit/f9041d1f765fa03f048a0f9cb38d052130468bb7#diff-19ed1f688a9c5481f9748fcc95f43b79R191

**Comment by spectrum70** [comment]
Hi all, i have this same issue on telegram 1.7.13 on linux. Since you marked issue as solved i guess the issue is in some OS settings. Any workaround is aprpeciated.

**Comment by buzzer13** [comment]
For anyone still having this issue. Please, double check your telegram's profile folder for logs. I accidentally found out there, that telegram (or something else) generated its own fontconfig settings in the profile dir. Probably these are leftovers of official telegram build or something, but after removing `fc-custom-1.conf` fonts finally became fine (both in tray menu and processes, spawned by telegram).

```
[2019.08.08 21:31:25] Working dir: /home/haze/.local/share/TelegramDesktop/
[2019.08.08 21:31:25] Command line: telegram-desktop
[2019.08.08 21:31:25] Executable path before check: /usr/bin/telegram-desktop
[2019.08.08 21:31:25] Logs started
[2019.08.08 21:31:25] Fontconfig version: 2.13.1.
[2019.08.08 21:31:25] Custom FONTCONFIG_FILE: /home/haze/.local/share/TelegramDesktop/tdata/fc-custom-1.conf
```

![yeeeeeeahhh](https://user-images.githubusercontent.com/5318721/62729027-c7ca7000-ba25-11e9-98e3-1dc7277ebe4e.png)

**Comment by hebrewd** [comment]
@buzzer13 Thanks! it was the same for me with hebrew fonts.
However, the fc-custom-1.conf file kept on reappearing, so I just left it there and removing reading permissions from the file. seems to do the trick.

**Comment by arielnmz** [comment]
Removing the file or the read permissions doesn't seem to be working for me. I keep seeing that ugly serif font in the context menu in the taskbar icon. 

![image](https://user-images.githubusercontent.com/24735547/72688487-64ad3100-3acd-11ea-99af-342778da40ef.png)
